spring:
 datasource:
   url: jdbc:postgresql://localhost:5434/Customer
   username: customer
   password: 12345
 jpa: 
   show-sql: true
   hibernate:
     ddl-auto: create-drop

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/     
