spring:
  cloud:
   gateway:
    routes:
     route:
      id: customer-service
      url: lb://customer-service
      predicates:
       - Path=/api/v1/customer/**
      filters:
       - name: JwtAuthenticationFilter
      
#  main:
#   allow-circular-references: true  
  
# management:
#  endpoints:
#   web:
#    exposure:
#     include: health,info,metrics

server:
  port: 9090
  
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/


  
      
