server:
  port: 9090

spring:
  cloud:
    gateway:
       discovery:
        locator:
          enabled: true 

          

logging:
  level:
    com.sadatscode.gatewayservice.filter: TRACE
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
     
  
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/


  
      
