spring:
  cloud:
   gateway:
    routes:
     route:
      id: customer-service
      uri: lb://CUSTOMER-SERVICE
      predicates:
       - Path=/api/v1/customer/**
      filters:
       - name: jwtAuthenticationFilter

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
     
#  main:
#   allow-circular-references: true  
  
management:
 endpoints:
  web:
   exposure:
    include: gateway

server:
  port: 8083
  
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/


  
      
