server:
  port: 9090

spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customer/**
          filters:
            - name: JwtAuthenticationFilter

        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/api/v1/user/**

       discovery:
        locator:
          enabled: true       

logging:
  level:
    com.sadatscode.gatewayservice.filter: TRACE
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
     
  
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/


  
      
