server:
  port: 9090

spring:
  main:
   allow-circular-references: true  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    # routes:
    #  - id: customer-service
    #    uri: http://localhost:8081
    #    predicates:
    #      - Path=/api/v1/customer/**
    #    filters:
    #     - name: JwtAuthenticationFilter

logging:
  level:
    root: INFO
    com.sadatscode.gatewayservice.filter: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
     

  
management:
 endpoints:
  web:
   exposure:
    include: gateway
  
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/


  
      
