spring:
  application:
    name: security-service
  data:
    redis:
     host: localhost
     port: 6380
     client-type: lettuce
     password: redis_bank_pass
     timeout: 60000
  datasource:
    url: jdbc:postgresql://localhost:5433/USERS
    username: security
    password: 12345
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      
  mail:
    port: 587
    host: smtp.gmail.com
    username: memmedlisedat033@gmail.com
    password: ghfs orqj yyyf envz
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true 
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/   
  # instance:
  #   hostname: localhost
  #   instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  
accessToken:
  expiredTime: 600000
  
refreshToken:
  expiredTime: 2592000000
  
server:
 port: 8080
 
# secret:
#   private-key: |
#     -----BEGIN RSA PRIVATE KEY-----
#     MIIEowIBAAKCAQEAiSn4hrk8t4lMbaj4Q4F3ktFZ+2V/6vxQNU4YtKuHdE1qhYkY
#     LIS4pdhZ9mdwaPeOW1sZ63uUWdTg/dB25TPUe8VdJr/76GGTzd0nhlYTwv0BsYlK
#     b4v6G9e4jrW7M1R/IDVoYyDs+XgAzx3qSKHm7jgXnxAEVADql7bKuw9Xw9vhgGOP
#     pzXgTvS5+wDfpheAw/Scit2C0g34s275bnpy6n2j5WC1ewOaHHIk9YPOrPiBy99P
#     3+C3hnIQFFseBSXZ+HqNsAo1g+6vZaV1/ieF7KOsl1VbqgQYsMKuJKUzDwvBHWk4
#     1BC/SmBfZv29Lm94jv1s90u2Gchu5qi211/vaQIDAQABAoIBAFbwp3qdhwK+oBcR
#     9uqy8Vu6HtLeLwp/C0f+TGKYJq9tMouZrhzpszBLxhoMzo95+l2ljPRZzFp0OHgo
#     3nPBOnmJS9X38nAFCW5/M0JO5Q++1of1gZzamJl1TqIGRrXuZPXBZH0QraQikEC3
#     sXyAQqPUIgTMXjHwssGfNzkCLJsTnbtDdiitCxDYzNVaoG+Zn2oD8JrMwsT2BJIQ
#     1ka0RHi/slvgRh+k5U4H73dZ7tHQe1rOAjeBkcC6TUui/We9VCJNtgIGcepm9S1A
#     /rZlI+Pp3JJfhxTQJr9ISnZVUYZgrqxM1TI1nSQx2WJHAFoWOOcr5Z9Z7gSS1a0u
#     LkH+WxECgYEA5MfQ9weyD0SrKAcHKT9OiQrEEkxoaRunjdtBl+c436qxC+QejncD
#     UGHVneIMpI5LdwKNoBj5cndh703BhQnJYkZ1EcGlKcOB9WZ3MhewB8ucYPtH2LQf
#     oVrTnnQOWQUnBshArgCWfSTFn0ryx9Srz4MZfF64NMjba0Ln5B3j5dsCgYEAmXuz
#     vjC2vzsF6uetjgJxaeJWBJgnXcmsGJu/x+HCO8gLPL/xHMk29Ttt+jmXhJDQaLX7
#     /mElSKTK3v7AyUGZerrPeNOrmOXQlxCrZMODPLLtNi+8Zqi9X1qS+rIYJZIsxq09
#     PWdEbLuJqFhizFMkWPi7T2h8JvrKSrVOOXGl3QsCgYA3ynqtI1VK3+YVVtFqP6P5
#     S4TRKYz0xOexclymnJ6D/O48Bh9lgqRuP82GOQ/4OTMyDI9ZEX4TagWaBA5DUUWp
#     D6GQ+PY8Hw9cNuaucpRc8kxqYhz9Pb/Q64NbytWM4/LGdqM/S6lnT0ZaOD7IeJaF
#     fmUCrV6ikLDhkWlXeeqPrQKBgDurixLLD5FDGibcUW4fZwZaV0TL/qoIyN58VtAX
#     5hKl0DCbEts1IyeuJjCdCVohjtTWw5R/Iiae4rxVYJAd79R2IkkASftUhYbllSzE
#     khYcHfruDhn/SjhzFydd6+NXdA79tQxVRJXdR0RqsGZtgHkSoofZwELLR7BJ0pKk
#     q25HAoGBAIvBBd4nWSflkMRWkYY4iflf3sP5+kPYN4n0R6CHkrBsTsyCu1AlazOy
#     3tq4GjKlfa146+PCdH6opMBcZK42Ijd4+87Kvy40guVCva/Jtel39gifKI/VLOEA
#     nHHujmXyQuZ7tK0JF8bwKlYm7wTXDE722GzlvFtLpQ2vAIVfe0gr
#     -----END RSA PRIVATE KEY-----
#  public-key: |
#    -----BEGIN PUBLIC KEY-----
#    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiSn4hrk8t4lMbaj4Q4F3
#    ktFZ+2V/6vxQNU4YtKuHdE1qhYkYLIS4pdhZ9mdwaPeOW1sZ63uUWdTg/dB25TPU
#    e8VdJr/76GGTzd0nhlYTwv0BsYlKb4v6G9e4jrW7M1R/IDVoYyDs+XgAzx3qSKHm
#    7jgXnxAEVADql7bKuw9Xw9vhgGOPpzXgTvS5+wDfpheAw/Scit2C0g34s275bnpy
#    6n2j5WC1ewOaHHIk9YPOrPiBy99P3+C3hnIQFFseBSXZ+HqNsAo1g+6vZaV1/ieF
#    7KOsl1VbqgQYsMKuJKUzDwvBHWk41BC/SmBfZv29Lm94jv1s90u2Gchu5qi211/v
#    aQIDAQAB
#    -----END PUBLIC KEY-----


  
