spring:
  application:
    name: security-service
  datasource:
    url: jdbc:postgresql://localhost:5433/USERS
    username: security
    password: 12345
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/   
  # instance:
  #   hostname: localhost
  #   instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  
accessToken:
  expiredTime: 600000
  
refreshToken:
  expiredTime: 2592000000

secret:
 private-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAMOyzDxrHvCG1y+R
7tDQ6TN6eovHGvwAJbWPZJaQDgmbS+RVxQ8baKnyY/DhqgL3GG9W5wxIEe1zmx2n
MxAcOuTnD3xuCI2HBQIqSTRIFeZQb8c9GFfh4Va7s3nTLr/jRZnlW93QlkV1xwWF
f6idQ1i4715LgDBS3f4JY0TjlCmVAgMBAAECgYAJB6cE4qx6zL4BI+qxF/KqvWwK
JxXHqvoSdptdlygOqWvHDW4aVFlv/g8+fisqF9y4xnnCx1CMdFkj9SMWCzdsY9QN
4qiTCuEAvemdt/VaXigzc/oZdC14vdmNCKeZ5LYxGkKaaeavMneGF68EismddawK
ZwX69UsBG7lSEozIAQJBAORKZmVkX+uBCtuAFF52pcZdPpJi0pUaVtytAb/bQIrk
423zpVQGN/CAS/JVfqUqXiqsv/0E3xJ3DutGD+AXhiECQQDbc6vQj2DJOdbkQgt2
OtKHJVxKvzg9SqWEFHJ4hWXsAsKeX7Kv8M5wY8ya2+wvybg+5SbZ9mitnJJxNcZL
X0z1AkEA2kag3TU52W1KulEeKKv9GUsydrjybAoBH4Jz98NlVOhA5HJfk5VWiyfA
dfZ03utBmkAOWZf8yiT4KNCWgUc8wQJAfcwQ8b0+/hrp1G8Hov6VMGN6RF7ZHkls
GAqgk/XkNyZd6etxwumHbWXII/1tpvc7ZtJ1MvzNhLf8OmlZAlvfAQJAL+Xtpyil
yZmZLt8wwv9CZ0nYgRgW5p0QsuB2RmlVS5IsPIJHeCkxNe3v7jCmCFHL1lQXUnws
4fC1KYAoPcrGZQ==
 public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDDssw8ax7whtcvke7Q0OkzenqL
xxr8ACW1j2SWkA4Jm0vkVcUPG2ip8mPw4aoC9xhvVucMSBHtc5sdpzMQHDrk5w98
bgiNhwUCKkk0SBXmUG/HPRhX4eFWu7N50y6/40WZ5Vvd0JZFdccFhX+onUNYuO9e
S4AwUt3+CWNE45QplQIDAQAB
 
server:
 port: 8080
  
