spring:
  application:
    name: security-service
  datasource:
    url: jdbc:postgresql://localhost:5433/USERS
    username: security
    password: 12345
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/   
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
        
server:
 port: 8080
  
