spring:
  application:
    name: security-service
  data:
    redis:
     host: localhost
     port: 6379
     client-type: lettuce
     password: redis_bank_pass
     timeout: 60000
  datasource:
    url: jdbc:postgresql://localhost:5433/USERS
    username: security
    password: 12345
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      
  mail:
    port: 587
    host: smtp.gmail.com
    username: memmedlisedat033@gmail.com
    password: ghfs orqj yyyf envz
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true 
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/   
  # instance:
  #   hostname: localhost
  #   instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  
accessToken:
  expiredTime: 600000
  
refreshToken:
  expiredTime: 2592000000
  
server:
 port: 8080
 
secret:
 private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDB/AyhuGmfu5UPimXnIvHKTS6lexGEZNKD+jsm3fUxd4V2yPwf2LVKjgEPDyLFxx0v+MqMEbG0F/rqURFDFTQAMKRvdwVLdnOs0BSMyuPNeUQkvHPzD6XraFPRNxm8oxyfixVuBV3piQhBXOrqE2hfEMYekDVf4wppRY4W05s+C2eIX3wvcNm7wYfHQ/xi5thlY/9Lvs5yBz/wocfBGtx6Xyo9JQcO3vCPLnvAPjmSZSP8sc26kOhuLcNWOjlKNZTyI1QL81DrBwA4Iuu2zhAzfA7cAa51Kk8jALNSnNL/poOv1bX2wCEb13f47uUgf+jGYn3GmPSstOH+0wCmZP1xAgMBAAECggEAAjewmIbuWK3NGH1SWMYDzfZryYcekjURmcICG/mytkz9quflZ3MLkAGPcinP8cM64n/xZ1Bit9qEExqIBCx9cKDduVs6xZQCIqQqjvk5CVHZAUNA/1LjCH3T4vbyea9C6hE9xokjy6IWFMK0WgaMpXUQcbwf6xOiLGXH1/uVaUw0k3IEYV5BUYIHxJWKHKhm+eRZBIcIFh0bBQMa8LqcMm5up4qo90LMKUQE/ivJjdQYuZWqlo+oEixhEjwur5siHqxs73rZMtbtzbaTKILps3GWoxwyBqEyU145vsVazWLHEk9RLIs61/xjppSUvwYxr1TarcUzEA3u5ZN4LgXswQKBgQD5El29I81UJ1r1qDBl09508mfxvpj2xWN9YTlFyeQJK81FAe9tasbr0mJC7LZDz+Kw9z7fGm5CRs92bDrl8oNgejCE5iRTYRKRtFTpKXeUPF1wiyZEqZprbJO6mBVZPebrVi/dFniGFoE1eAQo5beBVEmPseOVjrigJEfrU224sQKBgQDHYWijIQjLY7eGOrwhZM5hmO5feYaXUgXOAn+RSs63caLCUoerpnA/UWtz8KEwxVda4//IeB16c9dvqilhzyP6qJVAf1g66s44Ad7s7mZoXcm91Y8wMUVe5V78s78VjjWVM8c2JQQty1E3N2SRsbzHXsccICeJRgJA9Bwn4qjAwQKBgG2xcAU/wktAteeg9geyorOAmtS162orDqEGc5HP05VSbCnrK0ZWE1uCoXH2DGObJ6xmh5L8cfjQdMgj7GCfSMrxpXKyZOcvxlzTPd4ePCLV3xUUw3rT80VCYWF5X1WZVJzqrVPCdLwhJzCkNbjJSuMzet5FKwUQATHOKLp0WMtRAoGAQ0bJKhJhh0/Ug4SaKqJ7SU9zT+AP3EufDc6mAP6/FgNQKkXy5aa5xYPRwEN4AJ72RQMeMiTlvYYNMe63G/vrZg8wnZzaxraocxmegVBIWfsbseS39kkJ4WWAUcDNP5bG2duo4spGyLUMaJdWZhsVWijPAtyOurFW3VgBkCvZSYECgYEAyCu/lJ4+ps1JcUdz0AFLW+gPEGCZ8EWe3KaIhcHk7teUUlC8dlaPTOmRJbGrlmw8ypmj7//qnR7RdyP/ChuYPnAy+VtNw+RM1VZhpjw2ed5q4JpBovzwpL5611rESNzkiuZRLhPZSfkdVUHgVfEe0vr5sHZBNc+Wjv7p3Khy8TU= 
 public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwfwMobhpn7uVD4pl5yLxyk0upXsRhGTSg/o7Jt31MXeFdsj8H9i1So4BDw8ixccdL/jKjBGxtBf66lERQxU0ADCkb3cFS3ZzrNAUjMrjzXlEJLxz8w+l62hT0TcZvKMcn4sVbgVd6YkIQVzq6hNoXxDGHpA1X+MKaUWOFtObPgtniF98L3DZu8GHx0P8YubYZWP/S77Ocgc/8KHHwRrcel8qPSUHDt7wjy57wD45kmUj/LHNupDobi3DVjo5SjWU8iNUC/NQ6wcAOCLrts4QM3wO3AGudSpPIwCzUpzS/6aDr9W19sAhG9d3+O7lIH/oxmJ9xpj0rLTh/tMApmT9cQIDAQAB
 

  
